spring:
  datasource:
    url: jdbc:mysql://10.10.10.105:3306/jboot_jsk?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: zziggu
    password: zziggu
  jpa:
    hibernate:
      ddl-auto: update
    
    generate-ddl: true
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    
  thymeleaf:
    cache: false

logging:
  level:
    org.hibernate: debug
    org.springframework: info
    org.zerock: debug